nelmio_api_doc:
  documentation:
    servers:
      - url: '%env(APP_URL)%'
        description: API over HTTPS
    info:
      title: Symfony API Starter
      description: This is the starter of an Symfony API app. Please change me!
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: [ ]

    paths:
      /api/auth:
        post:
          tags: [ 'security' ]
          summary: 'Basic authentication service.'
          description: 'Please use this service to authenticate users.'
          operationId: 'post_login'
          security: [ ]
          requestBody:
            description: 'User credentials for authentication'
            content:
              application/json:
                schema:
                  required: [ 'username', 'password' ]
                  properties:
                    username:
                      description: 'User email address'
                      type: 'string'
                      example: 'john@doe.com'
                    password:
                      description: 'User password'
                      type: 'string'
                      example: '*********'
                  type: 'object'
          responses:
            200:
              description: 'Returns authentication data'
              content:
                application/json:
                  schema:
                    properties:
                      token:
                        description: 'User token'
                        type: 'string'
                        example: 'token-example'
                    type: 'object'

            400:
              description: 'Invalid input'

            401:
              description: 'Unauthorized access'

            404:
              description: 'Resource not found'

            500:
              description: 'Internal server error'

      /api/auth/refresh:
        post:
          tags: [ 'security' ]
          summary: 'Basic cookie refresh service'
          description: 'Please use this service to refresh an cookie for an user'
          operationId: 'post_token_refresh'
          security: [ ]
          responses:
            200:
              description: 'Returns user new refresh token'
              content:
                application/json:
                  schema:
                    properties:
                      token:
                        description: 'User new token'
                        type: 'string'
                        example: 'new-token-example'
                    type: 'object'

            400:
              description: 'Invalid input'

            401:
              description: 'Unauthorized access'

            404:
              description: 'Resource not found'

            500:
              description: 'Internal server error'

      /api/auth/logout:
        post:
          tags: [ 'security' ]
          summary: 'Basic logout service'
          description: 'Please use this service to logout an user'
          operationId: 'post_token_logout'
          security: [ ]
          responses:
            200:
              description: 'Returns logout success'
              content:
                application/json:
                  schema:
                    properties:
                      code:
                        description: 'The code of the logout'
                        type: 'integer'
                        example: 200
                      message:
                        description: 'The message of the logout'
                        type: 'string'
                        example: 'The supplied refresh_token has been invalidated.'
                    type: 'object'

            400:
              description: 'Invalid input'

            401:
              description: 'Unauthorized access'

            404:
              description: 'Resource not found'

            500:
              description: 'Internal server error'
  areas: # to filter documented areas
    disable_default_routes: true
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

