framework:
  default_locale: ro
  enabled_locales: [ 'ro', 'ru' ]
  set_locale_from_accept_language: true
  set_content_language_from_locale: true
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks:
      - ro
