version: "3.8"

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '4306:3306'

  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./app:/var/www/symfony
    depends_on:
      - database
    ports:
      - '9000:9000'
    environment:
      DATABASE_URL: mysql://${MYSQL_USER:-symfony}:${MYSQL_PASSWORD:-!ChangeMe!}@database:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-symfony}?serverVersion=${MYSQL_VERSION:-8}&charset=${MYSQL_CHARSET:-utf8}

  nginx:
    image: nginx:stable
    ports:
      - '8001:80'
    volumes:
      - ./app:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database