doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '15'
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
      gedmo_translatable:
        type: attribute
        prefix: Gedmo\Translatable\Entity
        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
        is_bundle: false
      gedmo_translator:
        type: attribute
        prefix: Gedmo\Translator\Entity
        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translator/Entity"
        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
        is_bundle: false
    dql:
      string_functions:
        replace: DoctrineExtensions\Query\Mysql\Replace
        substring_index: DoctrineExtensions\Query\Mysql\SubstringIndex
        lpad: DoctrineExtensions\Query\Mysql\Lpad
        rpad: DoctrineExtensions\Query\Mysql\Rpad
        group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
        regexp: DoctrineExtensions\Query\Mysql\Regexp
        cast: DoctrineExtensions\Query\Mysql\Cast
        md5: DoctrineExtensions\Query\Mysql\Md5
        date: DoctrineExtensions\Query\Mysql\Date
        date_format: DoctrineExtensions\Query\Mysql\DateFormat
        extract: DoctrineExtensions\Query\Mysql\Extract
        now: DoctrineExtensions\Query\Mysql\Now

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
