nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: [ ]
    allow_headers: [ ]
    allow_methods: [ ]
    expose_headers: [ ]
    max_age: 0
    hosts: [ ]
    origin_regex: false
    forced_allow_origin_value: ~
    skip_same_as_origin: true
  paths:
    '^\/api\/':
      origin_regex: true
      allow_credentials: true
      allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
      allow_headers: [ 'Content-Type', 'Accept-Encoding', 'Cache-Control', 'Authorization', 'Accept-Language' ]
      allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'PATCH' ]
      expose_headers: [ 'X-Total-Count', 'X-Page-Number', 'Location', 'Link', 'Content-Disposition' ]
      max_age: 3600
    '^\/uploads\/':
      allow_origin: [ '*' ]
